export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_PAGE = 'FETCH_CHARACTER_PAGE';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_LOCATION_PAGE = 'FETCH_LOCATION_PAGE';
export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_EPISODE_PAGE = 'FETCH_EPISODE_PAGE';
